language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: 05zyONpzBmOu0VRQgN9Rxm3Dx5vShuhipZbFy1YACJVr//V9uDuiOPCIbc4U7B8kPyxCqBZKFacGqr250Vgd2wgTBFgOis5sFNQi1oiFh3g5Bw7qPcItC53Z4uryYt2sJmRRXgzJ5CDCmw3c6CGQPvi7wI2ENh1XHAYTypdGqdZ0S/UBtfnFTyhVaW1FIx17eeIorNxgDnlYTfGtZcZNH3xH6jR4EmJuAjNlX1MfiXWx0ML+7EVWxF6Mo4+xrey0iu9XRwpLQP+erjYwikDUsdok/m8lPNMDhmwgdbCow40qzT8kdjGTCNZ6KfXlO4pNxWcvqSILUycx/Q2b6NIsWS+v6OO5/VxH2Hfyj0GB/1OzyqTZvuIl3jbPcXDUxIRtYz7k+0+0v6W1oo2f5Gyx5J/pWUlMKvr9J7nw6EPCI4ddecKwiSXYdudkXgCeoa52yoPa96YrRfuMJW1myb0rfjkb2mNagujO/FyGYxMd4OCG1x/ML1aGP4ATfB04G9NmnIHJgKh+76kGZD3tZA87ZEhg5ZlJKBp0hzD5cBdFYMgHARaZjrxaLuOd07Nnirv8Qj/TQs5CefJR8wXDwGIySpd6hCKnAxI7FmJTcXfwXRs4+kqbgsHSPpvboyHPaCkaQGlAKtmdW/dCklr0O5ekPhT9ggbQTikq83T/5f0JQu4=
  app: stormy-harbor-85727
  on:
    repo: sjlutterbie/node-shopping-list-integration-tests
